front-end-by-rimantas/41-grupe-portfolio-react

- css/basic/base.css
- css/pages/home.css
- index.html
suformatuoti failai, atnaujinus json settings (auto format feature)
> formated files after json settings update

- css/basic/layout.css
- css/pages/home.css
- index.html
> Main layout #7

- css/basic/base.css
- css/components/header-underline.css
- css/pages/home.css
- index.html
> #30 h2 component, header styling, root colors

- css/components/app-plan.css
- css/components/button.css
- css/pages/home.css
- index.html
> #30 price section

- css/pages/home.css
- index.html
Logo and navigation links without dropdown menu.
We need to combine head and hero sections to additional new div and apply to it gradient and background image.
> header initial #45

- css/pages/home.css
- index.html
Pakeitimas iskraipo hero section
> header-to-hero

- css/components/app-plan.css
- css/pages/home.css
- index.html
perdariau layouta, kad graziai ant media gultu
> #30 price section major update

- css/pages/home.css
- index.html
(1) navbar toggler (hamburger) added, (2) responsive navbar (hidden-lg, visible-lg)
> navbar-toggler

- css/pages/home.css
- index.html
> Hero section #6

- css/pages/home.css
- index.html
(1) Refactored navbar div.'s, (2) Added pseudo elements. Thanks Jurgita!
> nav-refactoring-pseudo

- css/pages/home.css
- index.html
> 27 sapp working section

- css/pages/home.css
- index.html
> Nav dropdown hover

- css/basic/base.css
- css/pages/home.css
- index.html
> #33 major positioning and background

- index.html
Scroll-on-click works, smooth doesn't. Despite html {scroll-behavior: smooth;} is set in base.css.
> scrool-on-click

- css/pages/home.css
- index.html
> refactored paralax

- css/pages/home.css
- index.html
> 36 footer init

- css/basic/base.css
> 33 download section

- css/pages/home.css
- index.html
Missing icons animation and some responsive
> 36 footer style update

- css/components/mobile-menu.css
- css/pages/home.css
- index.html
- js/components/mobile-menu/mobile-menu.js
- js/pages/home.js
#46 main logic (inner nav not done yet)
> 46 mobile header

- css/components/mobile-menu.css
- index.html
- js/components/mobile-menu/mobile-menu.js
> corrected links, new overlay
